### ISSUE TITLE
 【出现错误】File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 910, in json

### ISSUE THREAD

**Issue by Whichbfj28** [WizisCool/AutoEUServerless#2]
#python3 -m pip install -r requirements.txt---正常安装依赖
#python3 main.py--出现错误。内容如下

🔄 [AutoEUServerless] 正在续费第 1 个账号
🔍 [AutoEUServerless] 检测到第 1 个账号有 1 台 VPS，正在尝试续期
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ceshi/AutoEUServerless-main/main.py", line 430, in <module>
    main_handler(None, None)
  File "/opt/ceshi/AutoEUServerless-main/main.py", line 413, in main_handler
    if not renew(sessid, s, passwd_list[i], k, mailparser_dl_url_id_list[i]):
  File "/opt/ceshi/AutoEUServerless-main/main.py", line 312, in renew
    pin = get_pin_from_mailparser(mailparser_dl_url_id)
  File "/opt/ceshi/AutoEUServerless-main/main.py", line 191, in get_pin_from_mailparser
    pin = response.json()[0]["pin"]
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] P�FxWG�D�X�[Content_Types].xml��MN�0���"�%nY ��vAa	�(0����ؖg�w{&i
        m�����X�(���)���F��;@1_����c)j�x/%��E��y�                                                                            �@�nbE�{��y��d۸l
c��Ib7����a/l٥P1:�q�r��j��j0A����u�"���(�	���W�M��)Tj�({ܲ�>�O��,X٭���>B��~׭�
                                                                                 ��Ӥ6�J=�oBZ����t��X4���Cg�,���QgmrL�ٯc�e��t��	Z�?����hPv����u�j���R������}�Cv��P�FxW�78�K 
           _rels/.rels���j�0
剩下的就是这样的乱码了

**Comment by Whichbfj28** [comment]
按照设置后的获取到的PIN码是xlsx格式。内容：
![image](https://github.com/WizisCool/AutoEUServerless/assets/47915665/6717070b-4b71-4166-82be-6299c3db6add)

**Comment by Whichbfj28** [comment]
邮件下载的地方。要选择json格式。默认的是xlsx格式
